library(data.table)
dt<-fread("household_power_consumption.txt")
dt<-subset(dt,dt$Date %in% c("1/2/2007","2/2/2007"))
dt$Date<-as.Date(dt$Date,"%d/%m/20%y")
dt$DateTime<-paste(dt$Date,dt$Time)
dt$posix<-as.POSIXct(strptime(dt$DateTime,"20%y-%m-%d %H:%M:%S"))
Sys.setlocale("LC_TIME","English")
with(dt,plot(posix,as.numeric(Sub_metering_1),type="l",xlab="",ylab="Energy sub metering",main=""))
with(subset(dt),points(posix,as.numeric(Sub_metering_2),type="l",col="red"))
with(subset(dt),points(posix,as.numeric(Sub_metering_3),type="l",col="blue"))
legend("topright",lty="solid", col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png")
dev.off()
