library(data.table)
dt<-fread("household_power_consumption.txt")
dt<-subset(dt,dt$Date %in% c("1/2/2007","2/2/2007"))
dt$Date<-as.Date(dt$Date,"%d/%m/20%y")
dt$DateTime<-paste(dt$Date,dt$Time)
dt$posix<-as.POSIXct(strptime(dt$DateTime,"20%y-%m-%d %H:%M:%S"))
Sys.setlocale("LC_TIME","English")
with(dt,plot(posix,as.numeric(Global_active_power),type="l",xlab="",ylab="Global Active Power (kilowatts)",main=""))
dev.copy(png,file="plot2.png")
dev.off()